# Generated by Django 5.0.7 on 2024-10-04 13:50

import anusha.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anusha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('pan', models.CharField(blank=True, max_length=12, null=True)),
                ('aadhar', models.CharField(max_length=12)),
                ('profession', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('acc_number', models.CharField(max_length=30)),
                ('acc_holder_name', models.CharField(max_length=30)),
                ('bank_name', models.CharField(max_length=30)),
                ('ifsc_code', models.CharField(max_length=40)),
                ('branch_name', models.CharField(max_length=20)),
                ('agreeCheck', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('pan', models.CharField(blank=True, max_length=12, null=True)),
                ('aadhar', models.CharField(max_length=12)),
                ('profession', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('agreeCheck', models.BooleanField(default=False)),
                ('dsaPhoto', models.ImageField(upload_to='', validators=[anusha.models.validate_image_file])),
                ('aadharFront', models.ImageField(upload_to='', validators=[anusha.models.validate_image_file])),
                ('aadharBack', models.ImageField(upload_to='', validators=[anusha.models.validate_image_file])),
                ('panCard', models.ImageField(upload_to='', validators=[anusha.models.validate_image_file])),
                ('bankDocument', models.ImageField(upload_to='', validators=[anusha.models.validate_image_file])),
            ],
        ),
    ]
