# Generated by Django 5.0.7 on 2024-10-04 14:33

import anusha.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anusha', '0002_dsa_franchise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchise',
            name='aadharBack',
            field=models.ImageField(upload_to='dsa/', validators=[anusha.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='aadharFront',
            field=models.ImageField(upload_to='dsa/', validators=[anusha.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='bankDocument',
            field=models.ImageField(upload_to='dsa/', validators=[anusha.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='dsaPhoto',
            field=models.ImageField(upload_to='dsa/', validators=[anusha.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='panCard',
            field=models.ImageField(upload_to='dsa/', validators=[anusha.models.validate_image_file]),
        ),
    ]
